// tslint:disable
/// <reference path="./custom.d.ts" />
/**
 * Calculator Service
 * HTTP service for adding numbers, a goa teaser
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/calc-api';

